name: Windows Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    env:
      FLUTTER_VERSION: "3.38.3"
      FLUTTER_PR: "175405.175406"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run setup.bat
        run: .\setup.bat
        shell: cmd

      - name: Run build.bat
        run: .\build.bat %FLUTTER_VERSION% %FLUTTER_PR%
        shell: cmd

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: flutter_windows_${{ env.FLUTTER_VERSION }}_PR${{ env.FLUTTER_PR }}
          path: flutter/**/flutter_windows.dll*
